# Generated by Django 3.1.6 on 2021-02-15 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.tee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('fir', models.BooleanField(default=False)),
                ('gir', models.BooleanField(default=False)),
                ('putts', models.IntegerField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.hole')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='scores.round')),
            ],
        ),
    ]
